apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-core-deployment
spec:
  selector:
    matchLabels:
      app: recipes-core
  template:
    metadata:
      labels:
        app: recipes-core
    spec:
      containers:
      - name: recipes-core
        image: recipes-core:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000
        # env:
        #   - name: RavenSettings__Urls
        #     valueFrom:
        #       secretKeyRef:
        #         name: recipe-secrets
        #         key: ravendb-urls
        #   - name: RavenSettings__DatabaseName
        #     valueFrom:
        #       secretKeyRef:
        #         name: recipe-secrets
        #         key: ravendb-database-name
        #   - name: Google__BucketName
        #     valueFrom:
        #       secretKeyRef:
        #         name: recipe-secrets
        #         key: google-bucket-name
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: recipes-core-service
spec:
  clusterIP: None
  type: LoadBalancer
  selector:
    app: recipes-core
  ports:
  - port: 5000
    targetPort: 5000
